export enum InputTypeEnum {
  text = 'text',
  password = 'password',
  checkbox = 'checkbox',
  radio = 'radio',
  number = 'number',
  email = 'email',
  date = 'date',
  file = 'file',
  hidden = 'hidden',
  image = 'image',
  month = 'month',
  range = 'range',
  reset = 'reset',
  search = 'search',
  submit = 'submit',
  tel = 'tel',
  time = 'time',
  url = 'url',
  week = 'week',
  color = 'color',
}